name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Ganti ke 'master' jika pakai master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload semua file di root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
