name: Deploy Tracer Study to GitHub Pages

on:
  push:
    branches: [ main ]  # Akan jalan saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload semua file di root

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
